
package Vistas;

import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {

   
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        ReestablecerPassword = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogin.setBackground(new java.awt.Color(255, 255, 255));
        btnlogin.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(0, 0, 153));
        btnlogin.setText("Iniciar Sesión");
        btnlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 190, 30));

        txtUsername.setToolTipText("");
        txtUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 2, true), "Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Arial", 0, 10), new java.awt.Color(51, 0, 153))); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 170, 40));

        txtPassword.setToolTipText("");
        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 2, true), "Contraseña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Arial", 0, 10), new java.awt.Color(51, 0, 153))); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IA3.2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 200));

        ReestablecerPassword.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        ReestablecerPassword.setForeground(new java.awt.Color(0, 51, 153));
        ReestablecerPassword.setText("Restablecer Contraseña");
        ReestablecerPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReestablecerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReestablecerPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ReestablecerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
    String username = txtUsername.getText();
        String password = txtPassword.getText();
        //2. Mostramos los valores por consola
        System.out.println("Username: " + username + ", password: " + password);
        if (username.isEmpty()||password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Hay campos sin diligenciar","¡ATENCIÓN!", JOptionPane.WARNING_MESSAGE);
        }else{
            System.out.println("Entra al else");
            if (username.equals("MisionTic")&& password.equals("Ciclo2")){
                System.out.println("entra if");
                JOptionPane.showMessageDialog(null, "Bienvenido al sistema");
                System.out.println("Bienvenido");
                
                
                //AddUserForm usermenu = new AddUserForm(this, rootPaneCheckingEnabled); 
                //UserMenu1 usermenu = new UserMenu1();
                //UserMenu usermenu = new UserMenu();
                UserMenu2 usermenu = new UserMenu2();
                System.out.println("Crea userMenu");
                usermenu.setVisible(rootPaneCheckingEnabled);
                System.out.println("despues de setVisible");
                this.dispose();
                /*UserMenu usermenu = new UserMenu();
                System.out.println("Crea userMenu");
                usermenu.setVisible(rootPaneCheckingEnabled);
                System.out.println("despues de setVisible");
                this.dispose();*/
            }else{
                System.out.println("entra else 2");
                JOptionPane.showMessageDialog(null, "ERROR" ,"Usuario o Contraseña no coinciden", JOptionPane.ERROR_MESSAGE);
            
            }
        
        }
        
        
    
    }//GEN-LAST:event_btnloginActionPerformed
     
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void ReestablecerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReestablecerPasswordActionPerformed
        ResetPassword resetpassword = new ResetPassword(this,true);
        resetpassword.setVisible(true);
    }//GEN-LAST:event_ReestablecerPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReestablecerPassword;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
